motors:
  R0:
    offset: 0.30837726593
    dir: -1
  R1:
    offset: -0.153398513794
    dir: 1
  L0:
    offset: -0.343551635742
    dir: -1
  L1:
    offset: -0.0488748550415
    dir: 1
linkages:
  R0: -45
  R1: 45
  L0: 45
  L1: -45
geometry:
  l1: 45 # length of proximal links
  l2: 25 # length of distal links
  beta: 135 # angle from l2 to finger surface
  l3: 58 # distance from distal joint to fingertip
  gamma: 153 # angle from l2 to fingertip
  # r: distance of distal joint to motor
  r_min_offset: 3 # r_min = sqrt(l1**2 - l2**2) + r_min_offset
  r_max_offset: 2 # r_max = l1 + l2 - r_max_offset