# object's geometry
object_length: 43 # mm
object_thickness: 3 # mm

# scooping parameters
gripper_tilt: 60 # angle of the gripper
gripper_height: 0.2 # in meter, initial height of gripper in world frame 
contact_distance: 150 # in mm, dist from gripper frame to surface when fingers are in contact
finger_position: 0.8 # dimensionless F position on the object from the scooping edge
thumb_prescoop_position: 0.2 # dimensionless prescoop position away from the scooping edge
gripper_center: 0.8 # gripper center line position on the object from the scooping edge
finger_stiffness: 100 # pos gain in motor space
thumb_stiffness: 60 # pos gain in motor space

# frame transformation parameters
T_tool_gripper: # homogeneous transformation matrix of Gripper frame relative to tool frame
  - [0 ,0 ,-1, 0]
  - [0, 1, 0, 0]
  - [1, 0, 0, 80]  #77.73 / 81.23
  - [0, 0, 0, 1]
# vector from gripper frame to left motor frame
P_gripper_MotorL: [0, -35, 0]
# vector from gripper frame to right motor frame
P_gripper_MotorR: [0, 35, 0]

# ur10 motion parameters
tcp_vel: 0.05
tcp_acc: 0.05