# object's geometry
object_length: 43 # mm
object_thickness: 3 # mm

# gripper parameters
gripper_tilt: 60 # (degree) angle of the gripper
contact_distance: 150 # (mm) dist from gripper frame to surface when fingers are in contact
finger_prescoop_position: 0.9 # dimensionless F position on the object from the scooping edge
thumb_prescoop_position: 0.2 # dimensionless prescoop position away from the scooping edge
gripper_center: 0.8 # gripper center line position on the object from the scooping edge
digits_speed: 100 # speed of the fingers (bandwidth of input position filter) 
finger_prescoop_stiffness: 30 # pos gain of finger before scoop
thumb_prescoop_stiffness: 60 # pos gain of thumb before scoop
finger_scoop_stiffness: 50 # pos gain of finger for scooping
thumb_scoop_stiffness: 80 # pos gain of thumb for scooping
finger_grasp_stiffness: 150 # pos gain of finger for grasping
thumb_grasp_stiffness: 150 # pos gain of thumb for grasping
digit_grasp_position: [155, 45] # digit position of grasping the object in motor frame

# arm's motion parameters
gripper_height: 0.25 # (meter) initial height of gripper in world frame 
init_vel: 0.05 # (m/s) velocity of tcp when initializing gripper pose
init_acc: 0.05 # (m/s^2) acceleration...
smack_vel: 0.4 # (m/s) velocity of tcp when approaching to the surface
smack_acc: 0.4 # (m/s^2) acceleration...
slow_dist: 0.02 # (meter) distance of gripper slowing down after collision
lift_vel: 0.4 # (m/s) velocity of tcp when lifting the object up from the surface 
lift_dist: 0.2 # (meter) distance of gripper lifted off from the surface
stop_acc: 5 # (m/s^2) deceleration of stopping the robot's motion

# frame transformation parameters
T_tool_gripper: # homogeneous transformation matrix of Gripper frame relative to tool frame
  - [0 ,0 ,-1, 0]
  - [0, 1, 0, 0]
  - [1, 0, 0, 77.73]
  - [0, 0, 0, 1]
# vector from gripper frame to left motor frame
P_gripper_MotorL: [0, -35, 0]
# vector from gripper frame to right motor frame
P_gripper_MotorR: [0, 35, 0]
