# object's geometry
object_length: 148 # mm Capable notbook
object_thickness: 8 # mm
# object_length: 130 # mm "design direct'
# object_thickness: 20 # mm

# prescooping parameters
gripper_tilt: 50 # (degree) angle of the gripper
gripper_height: 0.3 # (meter) initial height of gripper in world frame 
contact_distance: 145 # (mm) dist from gripper frame to surface when fingers are in contact
finger_prescoop_position: 0.7 # dimensionless F position on the object from the scooping edge
thumb_prescoop_position: 0.01 # dimensionless prescoop position away from the scooping edge
gripper_center: 0.5 # gripper center line position on the object from the scooping edge
finger_prescoop_stiffness: 100 # pos gain of finger before scoop
thumb_prescoop_stiffness: 150 # pos gain of thumb before scoop
init_vel: 0.05 # (m/s) velocity of tcp when initializing gripper pose
init_acc: 0.05 # (m/s^2) acceleration...
digits_speed: 500 # speed of the fingers (bandwidth of input position filter) 

# smack and scoop parameters
smack_vel: 0.3 # (m/s) velocity of tcp when approaching to the surface
smack_acc: 0.3 # (m/s^2) acceleration...
slow_dist: 0.02 # (meter) distance of gripper slowing down after collision
lift_vel: 0.3 # (m/s) velocity of tcp when lifting the object up from the surface 
lift_dist: 0.22 # (meter) distance of gripper lifted off from the surface
stop_acc: 5 # (m/s^2) deceleration of stopping the robot's motion
finger_scoop_stiffness: 150 # pos gain of finger for scooping
thumb_scoop_stiffness: 150 # pos gain of thumb for scooping
finger_grasp_stiffness: 300 # pos gain of finger for grasping
thumb_grasp_stiffness: 300 # pos gain of thumb for grasping
digit_grasp_position: [145, 60] # digit position of grasping the object in motor frame

# frame transformation parameters
T_tool_gripper: # homogeneous transformation matrix of Gripper frame relative to tool frame
  - [0 ,0 ,-1, 0]
  - [0, 1, 0, 0]
  - [1, 0, 0, 77.73]
  - [0, 0, 0, 1]
# vector from gripper frame to left motor frame
P_gripper_MotorL: [0, -35, 0]
# vector from gripper frame to right motor frame
P_gripper_MotorR: [0, 35, 0]
